#!/bin/env bash

curl -X GET "https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=0x4b86e0295e7d32433ffa6411b82b4f4e56a581e1&vs_currencies=usd&include_market_cap=true&include_24hr_vol=true&include_24hr_change=true&include_last_updated_at=true" -H "accept: application/json" > ~/.config/awesome/tmp/dogira

cat ~/.config/awesome/tmp/dogira | jq .'[] | .usd'

